{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway
  annotations:
    {{- if .Values.security.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.security.tls.issuer | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
    nginx.ingress.kubernetes.io/limit-rps: "100"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.security.tls.enabled }}
  tls:
    - hosts: [ {{ .Values.ingress.host | quote }} ]
      secretName: {{ .Release.Name }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api-gateway
                port:
                  number: 8080
{{- end }}
